### ISSUE TITLE
Setting empty string

### ISSUE THREAD

**Issue by halv00rsen** [RadioRevolt/DABelFish#10]
The program chrashes when input is empty string.

**Comment by boyeln** [comment]
no, it does not? It produces an error on the server, which is passed on to the user and displayed in a sAlert box. But the program does not crash?

**Comment by boyeln** [comment]
The error is displayed in the server-side console, which is unfortunate and should be fixed.

**Comment by halv00rsen** [comment]
No does not crash, but showing an error in the server console
