### ISSUE TITLE
Boye VS. GLaDOS

### ISSUE THREAD

**Issue by boyeln** [RadioRevolt/DABelFish#56]
It was an epic battle, but I lost.

<img width="788" alt="skjermbilde 2016-01-21 kl 10 02 14" src="https://cloud.githubusercontent.com/assets/6630430/12476033/30d0a440-c027-11e5-952e-116f234fd2e3.png">

I think it's the ugly cron from 985d6198618c58d9bf08d4811675d7f642d6cc70. It is no longer needed, and should be removed.

**Comment by boyeln** [comment]
Yeah, the cron is including both sides of the time interval specified, so this line:

``` javascript
return parser.cron('0/10 * 0-7 * * *', true);
```

makes the cron run from 00:00:00 to 07:59:50.
this cron should be removed completely.

**Comment by N35N0M** [comment]
Nice work, there'll be cake.

2016-01-21 11:10 GMT+01:00 Boye Borg notifications@github.com:

> Yeah, the cron is including both sides, so this line:
> 
> return parser.cron('0/10 \* 0-7 \* \* *', true);
> 
> makes the cron run from 00:00:00 to 07:59:50.
> this cron should be removed completely.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RadioRevolt/DABelFish/issues/56#issuecomment-173524371
> .

## 

Med vennlig hilsen,
Kris Monsen
_MSc CS student, servicetekniker & studentradioprater_
_+47 400 44 908_
